version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: jira_postgres
    environment:
      POSTGRES_DB: jiradb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jira_network

  jira:
    image: atlassian/jira-software:latest
    container_name: jira
    depends_on:
      - postgres
    environment:
      ATL_JDBC_URL: jdbc:postgresql://postgres:5432/jiradb
      ATL_JDBC_USER: ${POSTGRES_USER}
      ATL_JDBC_PASSWORD: ${POSTGRES_PASSWORD}
      ATL_DB_DRIVER: org.postgresql.Driver
    ports:
      - "8080:8080"
    volumes:
      - jira_data:/var/atlassian/application-data/jira
    networks:
      - jira_network

volumes:
  postgres_data:
  jira_data:

networks:
  jira_network: